deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  install:
    - bundle install
  script: bundle exec rake deploy
  on:
    branch: master
